### ISSUE TITLE
TODO: 9/8

### ISSUE THREAD

**Issue by shuban-789** [shuban-789/Orion#5]
TODO:

- [x] Fix root access vulnerability
- [x] Implement a config file system
- [x] Implement SSL encryption

**Comment by shuban-789** [comment]
Issue Finished
